spring:
  application:
    name: api-gateway

  cloud:
    consul:
      host: localhost   # o "consul" si lo corres en Docker
      port: 8500
      discovery:
        enabled: true

#    gateway:
#      routes:
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/api/order/**
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/product/**

server:
  port: 9000