spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost  #Se cambia localhost por mongodb para que funcione correctamente dockerizado, de lo contrario, el contenedor de docker no conecta con mongo
                        # También hay que configurar esto mismo en el MongoConfig.java
      port: 27017
      database: product-db
      username: root
      password: password
      authentication-database: admin
  cloud:
    consul:
      host: localhost     #cambiar a "consul" cuando se vaya a levantar en Docker
      port: 8500
      discovery:
        enable: true
        register: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never